#!/usr/bin/env node
/**
 * Write a user profile to a YAML file
 * Usage: echo '<profile_json>' | node write-profile.js <output_file> <has_social_repo>
 */

const fs = require('fs');

async function main() {
  const outputFile = process.argv[2];
  const hasSocialRepo = process.argv[3] === 'true';

  // Read profile JSON from stdin
  let input = '';
  for await (const chunk of process.stdin) {
    input += chunk;
  }

  const profile = JSON.parse(input);

  const yaml = `# Profile for ${profile.login} - auto-generated by feed-sync workflow
last_updated: ${new Date().toISOString().replace(/\.\d{3}Z$/, 'Z')}
login: "${profile.login || ''}"
name: "${(profile.name || '').replace(/"/g, '\\"')}"
bio: "${(profile.bio || '').replace(/\n/g, ' ').replace(/"/g, '\\"')}"
location: "${(profile.location || '').replace(/"/g, '\\"')}"
blog: "${profile.blog || ''}"
avatar_url: "${profile.avatar_url || ''}"
followers: ${profile.followers || 0}
following: ${profile.following || 0}
twitter_username: "${profile.twitter_username || ''}"
company: "${(profile.company || '').replace(/"/g, '\\"')}"
has_social_repo: ${hasSocialRepo}
`;

  fs.writeFileSync(outputFile, yaml);
  console.log(`Wrote profile: ${outputFile}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
